# Generated by Django 4.2.13 on 2024-06-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('ensayos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id_ordenTrabajo', models.AutoField(primary_key=True, serialize=False)),
                ('no_orden', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosPorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.servicio')),
            ],
            options={
                'unique_together': {('id_proyecto', 'id_servicio')},
            },
        ),
    ]
