# Generated by Django 4.2.13 on 2024-06-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiametrosCoeficiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d10', models.DecimalField(decimal_places=2, max_digits=10)),
                ('d30', models.DecimalField(decimal_places=2, max_digits=10)),
                ('d60', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cc', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id_ordenTrabajo', models.AutoField(primary_key=True, serialize=False)),
                ('no_orden', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos')),
            ],
        ),
    ]
