# Generated by Django 3.2 on 2024-06-08 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_diametroscoeficiente_id_granulometria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiametrosCoeficiente',
        ),
    ]
