# Generated by Django 3.2 on 2024-06-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_delete_diametroscoeficiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
