# Generated by Django 3.2 on 2024-06-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_proyectos_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
