# Generated by Django 4.2.13 on 2024-06-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0012_servicio'),
        ('clientes', '0001_initial'),
        ('proyectos', '0008_ordentrabajo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id_ordenTrabajo', models.AutoField(primary_key=True, serialize=False)),
                ('no_orden', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosPorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='cliente',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='id_cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='OrdenTrabajo',
        ),
        migrations.AddField(
            model_name='serviciosporproyecto',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos'),
        ),
        migrations.AddField(
            model_name='serviciosporproyecto',
            name='id_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.servicio'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos'),
        ),
        migrations.AlterUniqueTogether(
            name='serviciosporproyecto',
            unique_together={('id_proyecto', 'id_servicio')},
        ),
    ]
