# Generated by Django 4.2.13 on 2024-05-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_area', models.CharField(max_length=255, unique=True)),
                ('nombre_area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.TextField()),
                ('cliente', models.TextField()),
                ('operador', models.TextField()),
                ('descripcion', models.TextField()),
                ('no_sondeo', models.IntegerField()),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('tipo', models.TextField()),
                ('codigo_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.area')),
            ],
        ),
        migrations.CreateModel(
            name='FactoresLL',
            fields=[
                ('id_factor', models.IntegerField(primary_key=True, serialize=False)),
                ('N', models.IntegerField()),
                ('K', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mallas',
            fields=[
                ('id_malla', models.IntegerField(primary_key=True, serialize=False)),
                ('medida', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LimitePlastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipiente_no', models.IntegerField()),
                ('pw_mas_recip', models.FloatField()),
                ('ps_mas_recip', models.FloatField()),
                ('agua', models.FloatField()),
                ('ps_mas_recip2', models.FloatField()),
                ('recipiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_seco', models.FloatField()),
                ('limite_plastico', models.FloatField()),
                ('id_ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.ensayo')),
            ],
        ),
        migrations.CreateModel(
            name='LimiteLiquido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_golpes', models.IntegerField()),
                ('recipiente_no', models.IntegerField()),
                ('pw_mas_recip', models.FloatField()),
                ('ps_mas_recip', models.FloatField()),
                ('agua', models.FloatField()),
                ('ps_mas_recip2', models.FloatField()),
                ('recipiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_seco', models.FloatField()),
                ('Pe_agua', models.FloatField()),
                ('limite_liquido', models.FloatField()),
                ('id_ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.ensayo')),
                ('id_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.factoresll')),
            ],
        ),
        migrations.CreateModel(
            name='Granulometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PeRP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PeQP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.ensayo')),
                ('id_malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.mallas')),
            ],
        ),
    ]
