# Generated by Django 4.2.13 on 2024-06-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ensayos', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayoslaboratorio',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos'),
        ),
        migrations.AddField(
            model_name='diametroscoeficiente',
            name='id_ensayo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ensayos.ensayoslaboratorio'),
        ),
    ]
