# Generated by Django 3.2 on 2024-05-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mallas',
            name='medida_mm',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
