# Generated by Django 4.2.13 on 2024-06-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayoslaboratorio',
            name='id_servicio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ensayos.servicio'),
            preserve_default=False,
        ),
    ]
