# Generated by Django 3.2 on 2024-05-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0002_mallas_medida_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallas',
            name='medida_mm',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
