# Generated by Django 4.2.13 on 2024-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0003_alter_mallas_medida_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayo',
            name='no_muestra',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='cliente',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='operador',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='tipo',
            field=models.TextField(null=True),
        ),
    ]
