# Generated by Django 4.2.13 on 2024-05-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0004_ensayo_no_muestra_alter_ensayo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoresll',
            name='K',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
