# Generated by Django 4.2.13 on 2024-06-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0004_ensayoslaboratorio_no_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='url_agregar',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ensayoslaboratorio',
            name='operador',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.CharField(max_length=40),
        ),
    ]
