# Generated by Django 3.2 on 2024-06-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('ensayos', '0005_alter_factoresll_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayo',
            name='id_ordenTrabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.ordentrabajo'),
        ),
    ]
