# Generated by Django 3.2 on 2024-06-08 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0006_ensayo_id_ordentrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiametrosCoeficiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d10', models.DecimalField(decimal_places=2, max_digits=10)),
                ('d30', models.DecimalField(decimal_places=2, max_digits=10)),
                ('d60', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_granulometria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ensayos.granulometria')),
            ],
        ),
    ]
