# Generated by Django 3.2 on 2024-06-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0008_alter_diametroscoeficiente_id_granulometria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diametroscoeficiente',
            old_name='id_granulometria',
            new_name='id_ensayo',
        ),
    ]
