# Generated by Django 3.2 on 2024-06-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_remove_proyectos_ubicacion'),
        ('ensayos', '0009_rename_id_granulometria_diametroscoeficiente_id_ensayo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensayo',
            name='id_ordenTrabajo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos'),
        ),
    ]
