# Generated by Django 3.2 on 2024-06-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0010_alter_ensayo_id_ordentrabajo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ensayo',
            old_name='id_ordenTrabajo',
            new_name='id_proyecto',
        ),
    ]
