# Generated by Django 4.2.13 on 2024-06-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0011_rename_id_ordentrabajo_ensayo_id_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=255)),
                ('codigo_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.area')),
            ],
        ),
    ]
