# Generated by Django 4.2.13 on 2024-06-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='nombres',
        ),
        migrations.AddField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
